DB_NAME = r'DB'
# WP_URL = 'https://olimpslots.com/xmlrpc.php'
# WP_USERNAME = 'olimpslots_c'
# WP_PASSWORD = 'ZIxdwcAjYEHnn2Xr'
WP_URL = 'https://sgzt.com/xmlrpc.php'
WP_USERNAME = 'rimmaruslan98@gmail.com'
WP_PASSWORD = ':Qs00u55'
openai_api_key = ''
TELEGRAM_BOT_TOKEN = "7091373217:AAG9cIbfToq5SKqcQzBeKByniBGxNePLlA0"
TELEGRAM_CHAT_ID = "1911446924" 
